# Generated by Django 5.1.1 on 2024-11-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_newtestimonial_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
