# Generated by Django 5.1.1 on 2024-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_experience_delete_service_delete_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='NewTestimonial',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
