# Generated by Django 5.1.1 on 2024-11-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_education_delete_newtestimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
