# Generated by Django 5.1.1 on 2024-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_testimonial_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
